### ISSUE TITLE
Find a way to promote team discussions/help (forum, slack, gitter, google goups...)

### ISSUE THREAD

**Issue by belgattitude** [belgattitude/soluble-japha#25]
Github is wonderful... but I feel the need to get a place to promote team discussions or general help requests. So I'm currently looking for advices on what would be the most easiest ways to get a central place for this project...

I made up a list of possible options like 
- A forum (which one ?)
- A dedicated google group
- Slack or gitter (discussions)

I'm really to open every good (even bad) ideas.. So, please, comment this issue with yours

**Comment by diegosainz** [comment]
In my experience Google Groups usually work well enough - one for development, the other for support. From there creating GitHub issues and the related tasks with a link to the discussion thread is enough to provide context.

I maybe would wait a little before creating another communication channel until the community around the project requires it (to avoid creating extra work on the maintenance of those channels)
