### ISSUE TITLE
I get an adapter but no functionality

### ISSUE THREAD

**Issue by ChrisChurch** [belgattitude/soluble-japha#27]
With this code and the JavaBridge war deployed to Tomcat 7 (I can get to  Javabridge  via a browser) :

public function bridgeAction ()
	{
		
		$options = [
				'driver' => 'Pjb62',
				'servlet_address' => 'xxx.yy.zz.251:8080/JavaBridge'
		];
		
		try {
		
			$ba = new BridgeAdapter($options);
			Debug::dump($ba);
			
			$string = $ba->java('java.lang.String', "保éà");

I get this result: 

object(Soluble\Japha\Bridge\Adapter)#1558 (3) {
  ["driver":protected] => object(Soluble\Japha\Bridge\Driver\Pjb62\Pjb62Driver)#1560 (3) {
    ["connected":protected] => bool(false)
    ["pjbProxyClient":protected] => object(Soluble\Japha\Bridge\Driver\Pjb62\PjbProxyClient)#1561 (4) {
      ["defaultOptions":protected] => array(5) {
        ["java_disable_autoload"] => bool(false)
        ["java_prefer_values"] => bool(true)
        ["java_log_level"] => NULL
        ["java_send_size"] => int(8192)
        ["java_recv_size"] => int(8192)
      }
      ["classMapCache":protected] => array(0) {
      }
      ["compatibilityOption":protected] => NULL
      ["options"] => array(7) {
        ["driver"] => string(5) "Pjb62"
        ["servlet_address"] => string(29) "178.62.73.251:8080/JavaBridge"
        ["java_disable_autoload"] => bool(false)
        ["java_prefer_values"] => bool(true)
        ["java_log_level"] => NULL
        ["java_send_size"] => int(8192)
        ["java_recv_size"] => int(8192)
      }
    }
    ["logger":protected] => object(Psr\Log\NullLogger)#1559 (0) {
    }
  }
  ["system":protected] => NULL
  ["logger":protected] => object(Psr\Log\NullLogger)#1559 (0) {
  }
}

Fatal error: unknown error: please see back end log for details in /var/www/Starlight/vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/SocketHandler.php on line 100

**Comment by belgattitude** [comment]
Bit confused about the issue, might be an utf8 issue or a server config. 

-----
**Server issue scenario:** Most probable

Add a suffix to your servlet address  like ...**/servlet.phpjavabridge**

i.e.

```php
$options = [
    'driver' => 'Pjb62',
    'servlet_address' => 'xxx.yy.zz.251:8080/JavaBridge/servlet.phpjavabridge'
];
```

-----
**UTF8 issue scenario:** ensure this works:
```
$javaString = $ba->java('java.lang.String', "ABC");
echo $javaString;
```
If the problem disappear, check that for your php default_charset is UTF-8:
```
echo init_get('default_charset'); // should print 'UTF-8'
```
_To work with UTF-8, default charset must be in UTF-8 as well, it shouldn't produce the error you had (shutdown broken connection) but good to test_ 



Let me know and I'll go deeper... and give me the PHP version you're working on, it helps to reproduce.

**Comment by belgattitude** [comment]
If you work on *nix, could be great if you can run the phpunit test, I've just added the default charset as utf8 in [phpunit.xml.dist ini set](https://github.com/belgattitude/soluble-japha/blob/master/phpunit.xml.dist#L56)...

To run the unit test on dev-master, simply:

```shell
$ git clone https://github.com/belgattitude/soluble-japha.git
$ cd soluble-japha
$ composer update --dev
$ composer test
# "composer test" executes "./vendor/bin/phpunit"
```
By default, the test suite will run with the embedded "pjbserver-tools standalone server"... If tests succeeds you can copy of `phpunit.xml.dist` to `phpunit.xml` and modify the lines:

```xml
<server name="AUTORUN_PJB_STANDALONE" value="false" />
<server name="PJB_SERVLET_ADDRESS" value="http://[SERVER_IP_ADDRESS]/JavaBridge/servlet.phpjavabridge" />
```

To specify your servlet install, then re-run the test suite with `composer test`

More info I have, better it is ;)

**Comment by ChrisChurch** [comment]
Hi

I have the standalone  running on a local Macbookpro and I can do in php:
 '$bigint = $ba->java("java.math.BigInteger", 1);
 echo $bigint->intValue() + 10; // prints 11' , 

at the moment I think my servlet issues are JVM version/JAR  issues - the code I have is stuff I did a while ago. FYI I use it to connect to a Quartz scheduler embedded in Tomcat - this is very useful - with access to a servlet function  I can set scheduled actions from a php script and it has worked well. 

public class MyScheduler extends HttpServlet {

public int ScheduleJob(String wowtype, ...

----------

(PHP 5.5.36 (cli) (built: May 29 2016 01:07:06)), results of phpunit are:

Chriss-MacBook-Pro:soluble-japha Chris$ php composer.phar test
> ./vendor/bin/phpunit
PHPUnit 4.8.29 by Sebastian Bergmann and contributors.
Warning:	The Xdebug extension is not loaded
		No code coverage will be generated.

................................I......................
Debug for java big memory test
Released memory must be approx equal to initial memory
- Initial memory   : 8,230,920
- Max memory       : 39,751,352
- After release    : 8,186,816

SSSSSS.... 65 / 73 ( 89%)
........

Time: 2.17 seconds, Memory: 249.50MB

OK, but incomplete, skipped, or risky tests!
Tests: 73, Assertions: 553, Skipped: 6, Incomplete: 1.

Notice: Uninitialized string offset: 6 in /Users/Chris/Documents/workspace/soluble-japha/src/Soluble/Japha/Bridge/Driver/Pjb62/EmptyChannel.php on line 123
Chriss-MacBook-Pro:soluble-japha Chris$ java -version 
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

**Comment by belgattitude** [comment]
Hi Chris, thanks a lot for sharing... really interesting idea.

If you think about a jvm/jar problem on the server side can be good to review [install notes for Tomcat](https://github.com/belgattitude/soluble-japha/blob/master/doc/install_server_j2ee.md) in the docs... I haven't wrote a solid manual yet, but you can also have some inspiration with the [this script](https://github.com/belgattitude/pjbserver-tools/blob/master/tools/jasper_bundle_bash/create_jasperbundle_war.sh) that helped me to build a .war file with jasper included.

I've also forked the server [here](https://github.com/belgattitude/php-java-bridge) to help building the bridge jar's. I'm thinking to document more when I have time, but all ideas or P/R are welcome and please let me know any issues.
