### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by holger-novadex** [belgattitude/soluble-japha#59]
Hello :-)
Are there any plans to support PHP 8 in near future?
Regards,
Holger

**Comment by belgattitude** [comment]
Yep I can update this week I think...

**Comment by belgattitude** [comment]
You can always try a P/R too :)

**Comment by holger-novadex** [comment]
Thanks for the effort! 

> You can always try a P/R too :)

Would love to do so, but unfortunately I'm extremely bussy ATM

**Comment by belgattitude** [comment]
@holger-novadex https://github.com/belgattitude/soluble-japha/pull/60, will fix ci this week but all seems to work pretty well.

**Comment by belgattitude** [comment]
@holger-novadex 

V3 released with PHP8 support https://github.com/belgattitude/soluble-japha/releases/tag/3.0.0

**Comment by blubberblah** [comment]
@belgattitude Thanks for the effort :-)
